language: ruby
dist: xenial
cache: bundler

before_install:
  # For testing purposes:
  - git config --global user.email "samuel@oriontransfer.net"
  - git config --global user.name "Samuel Williams"

matrix:
  include:
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.6
      env: COVERAGE=BriefSummary,Coveralls

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
    packages:
      - clang-4.0
      - libc++-dev
      - libc++abi-dev
env:
  - CC=clang-4.0 CXX=clang++-4.0
